#Even Fibonacci numbers
#Problem 2

#Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

#1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

#By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.

x = 1
b = 1
c = 0
arr = [1,2]

while c < 4000000:
	c = arr[b] + arr[b-1]
	arr.append(c)
	print c
	
	if x % 2 == 0:
		x += c
	b += 1
	if c > 20000000:
		 break


arr = 0
